version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    restart: always
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      CLUSTER_HOSTNAME: "node1"
      ENABLE_MODULES: "text2vec-openai,text2vec-transformers"
      TRANSFORMERS_INFERENCE_API: "http://t2v-transformers:8080"
      OPENAI_APIKEY: "your-openai-api-key" # Nếu dùng OpenAI, thay thế bằng API key thật
    volumes:
      - weaviate_data:/var/lib/weaviate
    depends_on:
      - t2v-transformers  # Nếu sử dụng text2vec-transformers

  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    container_name: t2v-transformers
    restart: always
    environment:
      ENABLE_CUDA: "0"  # Nếu có GPU, chuyển thành "1"
    ports:
      - "8081:8080"

volumes:
  weaviate_data:
